# /// script
# requires-python = ">=3.14"
# dependencies = ["pyyaml==6.0.3"]
# ///
"""Generate packages/ui/frontend/src/theme.css (shadcn/ui CSS variables) from _brand.yml.

    uv run scripts/brand_css.py

_brand.yml uses brand.yml's {light, dark} colour objects; this reads them directly, so the
R/Python brand_yml packages (which don't read that form) are not involved.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "packages" / "ui" / "frontend" / "src" / "theme.css"

# Roles brand.yml has no theme key for: a palette name per mode.
EXTRA = {
    "chip": {"light": "sand", "dark": "dark-hairline"},
    "hairline": {"light": "hairline", "dark": "dark-hairline"},
}
# shadcn token -> brand.yml theme key, or extra:<role>
TOKENS = {
    "background": "background", "foreground": "foreground",
    "card": "light", "card-foreground": "foreground",
    "popover": "light", "popover-foreground": "foreground",
    "primary": "primary", "primary-foreground": "background",
    "secondary": "extra:chip", "secondary-foreground": "foreground",
    "muted": "tertiary", "muted-foreground": "secondary",
    "accent": "extra:chip", "accent-foreground": "foreground",
    "destructive": "danger",
    "border": "extra:hairline", "input": "extra:hairline", "ring": "primary",
    "sidebar": "tertiary", "sidebar-foreground": "foreground",
    "sidebar-primary": "primary", "sidebar-primary-foreground": "background",
    "sidebar-accent": "extra:chip", "sidebar-accent-foreground": "foreground",
    "sidebar-border": "extra:hairline", "sidebar-ring": "primary",
    "brand-orange": "warning", "brand-success": "success",
}


def _resolve(palette: dict, value, mode: str) -> str:
    if isinstance(value, dict):
        value = value[mode]
    seen = set()
    while value in palette and value not in seen:  # palette entries may alias each other
        seen.add(value)
        value = palette[value]
    return value


def tokens(repo: Path, mode: str) -> dict[str, str]:
    color = yaml.safe_load((repo / "_brand.yml").read_text(encoding="utf-8"))["color"]
    out = {}
    for name, ref in TOKENS.items():
        value = EXTRA[ref.removeprefix("extra:")][mode] if ref.startswith("extra:") else color[ref]
        out[name] = _resolve(color["palette"], value, mode)
    return out


def _block(selector: str, values: dict[str, str], scheme: str, indent: str = "") -> str:
    lines = [f"{indent}{selector} {{", f"{indent}  color-scheme: {scheme};", f"{indent}  --radius: 0.5rem;"]
    lines += [f"{indent}  --{k}: {v};" for k, v in values.items()]
    return "\n".join(lines + [f"{indent}}}"])


def render(repo: Path) -> str:
    light, dark = tokens(repo, "light"), tokens(repo, "dark")
    return "\n".join([
        "/* Generated by scripts/brand_css.py from _brand.yml. Do not edit. */",
        _block(":root", light, "light"),
        _block(".dark", dark, "dark"),
        "/* Before the app picks a mode (class light/dark on <html>), follow the OS. */",
        "@media (prefers-color-scheme: dark) {",
        _block(":root:not(.light):not(.dark)", dark, "dark", indent="  "),
        "}",
        "",
    ])


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(REPO), encoding="utf-8")
    print(f"wrote {OUT}", file=sys.stderr)
